#!/usr/bin/env bash
#Script to install Nginx on Webserver when executed
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

echo 'Hello World' > /var/www/html/index.html
echo "server {
        listen  80 default_server;
        listen  [::]:80 default_Server;
        root    /var/www/html;
        index   index.html index.htm;        
}" > /etc/nginx/sites-available/default
sudo service nginx nginx restart
