#!/usr/bin/env bash
# Script to install Nginx on Webserver when executed
# This script also configures the default web page to be "Hello World"
# Also a redirect url has been added to /redirect_me, which redirect to my
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

NEW_REDIRECTION="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo sed -i "53i $NEW_REDIRECTION" /etc/nginx/sites-available/default
service nginx restart
