#!/usr/bin/env bash
# Script to install Nginx on Webserver when executed
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/error_404.html

NEW_REDIRECTION="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i "/^}/i $NEW_REDIRECTION" /etc/nginx/sites-available/default

NEW_REDIRECTION="\\\n\terror_page 404 /error_404.html;\n"

sudo sed -i "/^server_name _;/a $NEW_REDIRECTION" /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
