#!/usr/bin/env bash
#Script creates a backup of MySQL DB

# Get today's date in the desired format
CURRENT_DATE=$(date +"%d-%m-%Y")

# Create the backup.sql file
mysqldump -u root -p"$1" --all-databases > backup.sql
# Create the compressed archive
tar -czvf "$CURRENT_DATE.tar.gz" backup.sql
