#!/usr/bin/env bash
# displays numbers from 1 to 100 with the following requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number, In a list format
count=1
until [ $count -ge 100 ]; do
    if ($count/3)=0 and ($count/5)=0; then
        echo "FizzBuzz"
    elif ($count/3)=0; then
        echo "Fizz"
    elif ($count / 5)=0; then
        echo "Buzz"
    else
        echo $count
    fi
count=$((count + 1))
done