#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# The script displays only: username, user id, Home directory path for the user
filepath="/etc/passwd"
if [[ -f "$filepath" ]]; then
    while IFS= read -r line; do
        IFS=: read -ra fields <<< "$line"
        echo "The user ${fields[0]} is part of the ${fields[3]} gang, lives in ${fields[5]} and rides ${fields[6]}."
        echo "${fields[2]}'s place is protected by the passcode x, more info about the user here: ${fields[0]}"
        echo
    done < "$filepath"
else
    echo "File $filepath does not exist"
fi