#!/usr/bin/env bash
#Script uses for loop to list a file "School".
filename="school"
if [[ -f "$filename" ]]; then
    echo "School file exists"
        if [[ -s "$filename" ]]; then
            echo "School file is not empty"
        else
            echo "School file is empty"
        fi
        if [[ -f "$filename" ]]; then
            echo "School file is a regular file"
        fi
else
    echo "School file does not exist"
fi