#!/usr/bin/env bash
#Script uses for loop to list a file "School".
if [[ -e "School" ]]; then
    echo "School file exists"
        if [[ -s "school" ]]; then
            echo "School file is not empty"
        else
            echo "School file is empty"
        fi
        if [[ -f "school" ]]; then
            echo "School file is a regular file"
        fi
else
    echo "School file does not exist"
fi