#!/usr/bin/bash
# Script configures ufw firewall by blocking all
# incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)
# Allow  SSH
sudo ufw allow 22/tcp

# Allow HTTPS SSL
sudo ufw allow 443/tcp

# Allow HTTP
sudo ufw allow 80/tcp
