#!/usr/bin/bash
# Update package lists
sudo apt update

# Enable packet forwarding
echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/ufw/sysctl.conf
sudo sysctl -p

# Allow incoming traffic on port 8080
sudo ufw allow 8080/tcp

# Configure UFW NAT rule for redirection
sudo ufw allow proto tcp dport 8080 to destination any port 80 REDIRECT

# Enable UFW (if not already enabled)
sudo ufw enable
