#!/usr/bin/env bash
# Copy the old hosts file into hosts.new file
# Set localhost to resolve to 127.0.0.2
# Set facebook.com to resolve to 8.8.8.8
# Copy the hosts.new file into the running /etc/hosts file

  cp /etc/hosts ~/hosts.new
  echo "127.0.0.2		localhost" > ~/hosts.new
  echo "8.8.8.8		facebook.com" >> ~/hosts.new
  cp -f ~/hosts.new /etc/hosts
