#!/usr/bin/env bash
#Script that runs the whoami command under the user passed as an argument
# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Get the username from the argument
username=$1

# Check if the user exists
if id "$username" &>/dev/null; then
    # Run whoami command as the specified user
    sudo -u "$username" whoami
else
    echo "User '$username' does not exist."
fi
