#!/usr/bin/env bash
#Script that configures the container to fit the below requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Configure Nginx as user

sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen\s*\(.*\);/listen 8080;/' /etc/nginx/conf.d/default.conf

service nginx restart
