#!/usr/bin/env bash
#Script that configures the container to fit the below requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Configure Nginx as user
# Update nginx.conf to use nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the default port from 80 to 8080
sed -i "s/\<80\>/8080/g" /etc/nginx/sites-available/default

# Restart nginx service as the nginx user
sudo -u nginx service nginx restart
