#!/bin/bash
# Nginx Config

cat <<EOF
server {
	listen 80;
	listen [::]:80;
	
	add_header X-Served-By 230740-web-01;
	
	server_name localhost 54.172.62.80;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}

    location / {
        proxy_pass http://127.0.0.1:5003;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /static/ {
        alias /path/to/web_dynamic/static/;
        expires 30d;
    }

	location /api/ {
		proxy_pass http://127.0.0.1:5002/;
		proxy_set_header Host \$host;
		proxy_set_header X-Real-IP \$remote_addr;
	}
}
EOF
